services:
  app:
    build:
      context: ./userapi   # Spécifie le dossier contenant le Dockerfile
      dockerfile: Dockerfile # Indique explicitement le nom du Dockerfile
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
