---
- name: Configuration du serveur pour l'application Node.js
  hosts: all
  become: yes
  tasks:
    # Mise à jour du système
    - name: Mise à jour du cache apt
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Installation des paquets essentiels
      apt:
        name: 
          - curl
          - git
          - build-essential
        state: present

    # Installation de Node.js
    - name: Installation du dépôt Node.js
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      args:
        warn: false

    - name: Installation de Node.js
      apt:
        name: nodejs
        state: present

    # Installation de Redis
    - name: Installation de Redis
      apt:
        name: redis-server
        state: present

    - name: Configuration de Redis - Bind sur toutes les interfaces
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: '^bind 127\.0\.0\.1'
        line: 'bind 0.0.0.0'
        backup: yes

    - name: Redémarrage de Redis
      service:
        name: redis-server
        state: restarted
        enabled: yes

    # Configuration de l'application
    - name: Création du répertoire de l'application
      file:
        path: /opt/userapi
        state: directory
        mode: '0755'

    - name: Copie des fichiers de l'application
      synchronize:
        src: /vagrant/userapi/
        dest: /opt/userapi/
        rsync_opts:
          - "--exclude=node_modules"

    - name: Installation des dépendances de l'application
      npm:
        path: /opt/userapi
        state: present

    # Démarrage de l'application
    - name: Start application
      shell: |
        cd /opt/userapi
        npm start
      async: 1000
      poll: 0

    # Vérification de la santé
    - name: Vérification de la santé de l'application
      uri:
        url: http://localhost:3000/health
        return_content: yes
      register: health_check
      until: health_check.status == 200
      retries: 6
      delay: 10
