name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test Application
    runs-on: ubuntu-latest

    steps:
      # 1. Récupère le code source
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Installe Node.js (ou un autre runtime si nécessaire)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Installe les dépendances
      - name: Install Dependencies
        run: npm install

      # 4. Exécute les tests
      - name: Run Tests
        run: npm test

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      # 1. Récupère le code source
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Déploie l'application avec Docker Compose
      - name: Deploy with Docker Compose
        run: |
          docker-compose up -d
          echo "Application déployée avec succès !"
